/**
 * MUST MAKE TESTER FOR LINKED LIST STACK
 * PLANNING ON SOLVING PROBLEM BOTH WAYS
 * TRY TO USE JUNIT TESTING EVENTUALLY 
 * DELETE THIS BEFORE COMMITING
 */
/**
 * @author w7176516
 *
 */
package LinkedListStack;